name: Generate RS Rankings
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run RS scripts
      run: |
        echo "Running rs_data.py..."
        python rs_data.py > data_log.txt 2>&1 || { echo "rs_data.py failed"; cat data_log.txt; exit 1; }
        echo "Running rs_ranking.py..."
        python rs_ranking.py > ranking_log.txt 2>&1 || { echo "rs_ranking.py failed"; cat ranking_log.txt; exit 1; }
        ls -R > dir_list.txt
        cat dir_list.txt
    - name: Upload Debug Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-logs
        path: |
          data_log.txt
          ranking_log.txt
          dir_list.txt
    - name: Upload RS Output
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: rs-output
        path: output/
