name: Generate RS Rankings

# Triggers: Daily schedule + manual run
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu is fine for Python scripts

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4  # Update to v4 for latest features

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Match a common version

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Generate RS data and rankings
      - name: Run RS scripts
        run: |
          python rs_data.py || { echo "rs_data.py failed"; exit 1; }
          python rs_ranking.py || echo "rs_ranking.py failed"
          ls -R

      # Upload the output folder
      - name: Upload RS Output
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: rs-output
          path: output/
